version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:8080"
    links:
      - mongo
    networks:
      - badger_net
    volumes:
      - ./api:/usr/src/app/api
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - badger_net
networks:
  badger_net:
    driver: bridge
